-- Last updated: 12/08/2026, 12:18:15
CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
    SET N = N-1;
  RETURN (
     SELECT DISTINCT SALARY
     FROM Employee
     ORDER BY SALARY  DESC
     LIMIT 1 OFFSET N
  );
END